### ISSUE TITLE
Add support for 'children'

### ISSUE THREAD

**Issue by reinaldoviera1** [clubajax/react-web-component#1]
Using the component like this:

```html
<WebComponent component="chart-pie" header={title}>
 <p>It is excellent</p>
</WebComponent>
```

will cause an error:

`TypeError: Cannot assign to read only property 'children' of object '[object HTMLElement]'`

**Comment by clubajax** [comment]
ca74e1abb03f6aff87f848ea7e0ee7c294bb1020

Good suggestion. That feature has been added to version 1.0.0.
